# Generated by Django 5.0.6 on 2024-05-31 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messages',
            new_name='message',
        ),
    ]
